[package]
name = "rust_llm"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_llm"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
lazy_static = "1.4.0"
base64 = "0.22.1"
unicode_categories = "0.1"
